### PR TITLE
Common Units test

### PR DESCRIPTION
**Pull request by labkey-matthewb**
I started writing a little primitive test just to learn the API and realized it would be better if it fit into your existing test framework.

### CODE REVIEW

**Comment by grahamegrieve** [comment]
I don't understand what this test achieves?

**Comment by labkey-matthewb** [comment]
Hmm, it's been a minute.  I believe this was basically a test of suitability of using this library in conjunction with adopting usage of UCUM.   Obviously, this test is very simple, basically a smoke test (which I still find very helpful to have in any test suite).  It still turned up a few NullPointerExceptions that had to be avoided (see code).  The thrown UcumException might be expected or not, I don't remember.

**Comment by labkey-matthewb** [comment]
Meant do say "adopting usage of LOINC"

**Review by grahamegrieve — APPROVED** [review]
ok

**Comment by labkey-matthewb** [comment]
It might be worth commenting out the "if/continue" cases to see if the NPE's are still repro and need to be resolved.

**Pull request merged**
